More compatible with Windows
h2o/picotls pull request #375
Opened 2021-12-13 18:48 UTC by BernardoGomesNegri

This changes a few bits of the code to make the library compatible with Windows. It changes some included header files to point to the Windows equivalents, as well as adding some more definitions that are not avaliable on Windows that should act as a drop-in replacement for their POSIX equivalents.

2021-12-13 21:56 UTC, BernardoGomesNegri commented
CI failed, but it does work with mingw.

2021-12-14 01:59 UTC, huitema requested changes
What problem are you trying to solve? The xisting visuall studio code works well and has been in use for a long time. You may want to streamline it, but if you do that you should ensure that there is no regression in Visual Studio, and also no duplication of code in the resulting set.

For example: reconcile the proposed inclusion of gettimeofday with the code existing in "wintimeofday.c", which uses a more precise defintion of time than the proposed replacement. Also, track all usages of "wincompat.h", and either replace them all or replace none...

2021-12-14 01:59 UTC, huitema commented on lib/picotls.c
> +
gettimeofday is also used in ptlsbench. Are you going to leave that code use the old "wincompat.h", or do you want to export the signature and the defintion of timezone in another header?

2021-12-14 01:59 UTC, huitema commented on lib/picotls.c
> +
The replacement code proposed here is already defined in "wintimeofday.c", and the code has been used for the Visual Studio builds for a long time. We should not have two versions of that code in the same project. Also, the existing code uses "GetSystemTimePreciseAsFileTime", which achieves higher precision.

2021-12-14 14:09 UTC, closed without merging